//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadamRozikaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.CategoryArticleRelations = new HashSet<CategoryArticleRelation>();
            this.CommentArticleRelations = new HashSet<CommentArticleRelation>();
            this.TagArticleRelations = new HashSet<TagArticleRelation>();
        }
    
        public int ArticleId { get; set; }
        public int AuthorId { get; set; }
        public string Title { get; set; }
        public byte Status { get; set; }
        public string ArticleText { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime SortingDate { get; set; }
        public bool CommentActive { get; set; }
        public int Hit { get; set; }
        public byte Copyright { get; set; }
        public string Sites { get; set; }
    
        public virtual ICollection<CategoryArticleRelation> CategoryArticleRelations { get; set; }
        public virtual ICollection<CommentArticleRelation> CommentArticleRelations { get; set; }
        public virtual ICollection<TagArticleRelation> TagArticleRelations { get; set; }
    }
}
