//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadamRozikaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.CommentAuthorRelations = new HashSet<CommentAuthorRelation>();
        }
    
        public int AuthorId { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public byte Status { get; set; }
        public short MainPageStatus { get; set; }
        public string Sites { get; set; }
        public string NameUrl { get; set; }
        public string imageUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string FacebookUrl { get; set; }
        public string LinkedinUrl { get; set; }
        public string Embed { get; set; }
        public Nullable<short> Rank { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual ICollection<CommentAuthorRelation> CommentAuthorRelations { get; set; }
    }
}
