//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadamRozikaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryArticleRelations = new HashSet<CategoryArticleRelation>();
            this.CategoryGalleryRelations = new HashSet<CategoryGalleryRelation>();
            this.CategoryNewsRelations = new HashSet<CategoryNewsRelation>();
        }
    
        public int CategoryId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> MegaMenu { get; set; }
    
        public virtual ICollection<CategoryArticleRelation> CategoryArticleRelations { get; set; }
        public virtual ICollection<CategoryGalleryRelation> CategoryGalleryRelations { get; set; }
        public virtual ICollection<CategoryNewsRelation> CategoryNewsRelations { get; set; }
    }
}
