//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadamRozikaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryItem
    {
        public int ItemId { get; set; }
        public int GalleryId { get; set; }
        public string Summary { get; set; }
        public byte Type { get; set; }
        public string FilePath { get; set; }
        public int ItemOrder { get; set; }
    }
}
