//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadamRozikaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.CategoryNewsRelations = new HashSet<CategoryNewsRelation>();
            this.CommentNewsRelations = new HashSet<CommentNewsRelation>();
            this.TagNewsRelations = new HashSet<TagNewsRelation>();
        }
    
        public int NewsId { get; set; }
        public string Title { get; set; }
        public string TitleUrl { get; set; }
        public string SeoTitle { get; set; }
        public string SeoTitleUrl { get; set; }
        public string Summary { get; set; }
        public string NewsText { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> CommentActive { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public Nullable<int> VideoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Tags { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<byte> UserStatus { get; set; }
    
        public virtual ICollection<CategoryNewsRelation> CategoryNewsRelations { get; set; }
        public virtual ICollection<CommentNewsRelation> CommentNewsRelations { get; set; }
        public virtual ICollection<TagNewsRelation> TagNewsRelations { get; set; }
    }
}
