//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadamRozikaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.RoleUserRelations = new HashSet<RoleUserRelation>();
        }
    
        public int UserId { get; set; }
        public byte RoleId { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<RoleUserRelation> RoleUserRelations { get; set; }
    }
}
